/*
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListPriceListsResponsePriceList;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PricelistListPriceListsResponse
 */
public class PricelistListPriceListsResponseTest {
    private final PricelistListPriceListsResponse model = new PricelistListPriceListsResponse();

    /**
     * Model tests for PricelistListPriceListsResponse
     */
    @Test
    public void testPricelistListPriceListsResponse() {
        // TODO: test PricelistListPriceListsResponse
    }

    /**
     * Test the property 'pricelists'
     */
    @Test
    public void pricelistsTest() {
        // TODO: test pricelists
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

}
