/*
 * pricelist/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PricelistFilterCondition;
import org.openapitools.client.model.PricelistPriceListType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PricelistPriceListTypeFilter
 */
public class PricelistPriceListTypeFilterTest {
    private final PricelistPriceListTypeFilter model = new PricelistPriceListTypeFilter();

    /**
     * Model tests for PricelistPriceListTypeFilter
     */
    @Test
    public void testPricelistPriceListTypeFilter() {
        // TODO: test PricelistPriceListTypeFilter
    }

    /**
     * Test the property 'pricelistTypes'
     */
    @Test
    public void pricelistTypesTest() {
        // TODO: test pricelistTypes
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

}
