/*
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PricelistDeletePriceListItemsRequest
 */
public class PricelistDeletePriceListItemsRequestTest {
    private final PricelistDeletePriceListItemsRequest model = new PricelistDeletePriceListItemsRequest();

    /**
     * Model tests for PricelistDeletePriceListItemsRequest
     */
    @Test
    public void testPricelistDeletePriceListItemsRequest() {
        // TODO: test PricelistDeletePriceListItemsRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'itemsGrn'
     */
    @Test
    public void itemsGrnTest() {
        // TODO: test itemsGrn
    }

}
