/*
 * pricelist/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PricelistGetPriceListItem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PricelistGetPriceItemsByPriceListItemIdsResponse
 */
public class PricelistGetPriceItemsByPriceListItemIdsResponseTest {
    private final PricelistGetPriceItemsByPriceListItemIdsResponse model = new PricelistGetPriceItemsByPriceListItemIdsResponse();

    /**
     * Model tests for PricelistGetPriceItemsByPriceListItemIdsResponse
     */
    @Test
    public void testPricelistGetPriceItemsByPriceListItemIdsResponse() {
        // TODO: test PricelistGetPriceItemsByPriceListItemIdsResponse
    }

    /**
     * Test the property 'prices'
     */
    @Test
    public void pricesTest() {
        // TODO: test prices
    }

}
