/*
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PricelistCurrency;
import org.openapitools.client.model.PricelistPriceListType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PricelistCreatePriceListRequest
 */
public class PricelistCreatePriceListRequestTest {
    private final PricelistCreatePriceListRequest model = new PricelistCreatePriceListRequest();

    /**
     * Model tests for PricelistCreatePriceListRequest
     */
    @Test
    public void testPricelistCreatePriceListRequest() {
        // TODO: test PricelistCreatePriceListRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'isDefault'
     */
    @Test
    public void isDefaultTest() {
        // TODO: test isDefault
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'vatIncluded'
     */
    @Test
    public void vatIncludedTest() {
        // TODO: test vatIncluded
    }

    /**
     * Test the property 'deliveredDutyPaid'
     */
    @Test
    public void deliveredDutyPaidTest() {
        // TODO: test deliveredDutyPaid
    }

    /**
     * Test the property 'segments'
     */
    @Test
    public void segmentsTest() {
        // TODO: test segments
    }

    /**
     * Test the property 'markets'
     */
    @Test
    public void marketsTest() {
        // TODO: test markets
    }

    /**
     * Test the property 'channels'
     */
    @Test
    public void channelsTest() {
        // TODO: test channels
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'isSystem'
     */
    @Test
    public void isSystemTest() {
        // TODO: test isSystem
    }

}
