/*
 * PriceList Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PricelistFilterCondition;
import org.openapitools.client.model.PricelistPriceListType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Pricelist.JSON;

/**
 * PricelistPriceListTypeFilter
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-01T16:31:03.730775696Z[Etc/UTC]")
public class PricelistPriceListTypeFilter {
  public static final String SERIALIZED_NAME_PRICELIST_TYPES = "pricelistTypes";
  @SerializedName(SERIALIZED_NAME_PRICELIST_TYPES)
  private List<PricelistPriceListType> pricelistTypes;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  private PricelistFilterCondition condition = PricelistFilterCondition.IN;

  public PricelistPriceListTypeFilter() {
  }

  public PricelistPriceListTypeFilter pricelistTypes(List<PricelistPriceListType> pricelistTypes) {
    this.pricelistTypes = pricelistTypes;
    return this;
  }

  public PricelistPriceListTypeFilter addPricelistTypesItem(PricelistPriceListType pricelistTypesItem) {
    if (this.pricelistTypes == null) {
      this.pricelistTypes = new ArrayList<>();
    }
    this.pricelistTypes.add(pricelistTypesItem);
    return this;
  }

   /**
   * Get pricelistTypes
   * @return pricelistTypes
  **/
  @javax.annotation.Nullable
  public List<PricelistPriceListType> getPricelistTypes() {
    return pricelistTypes;
  }

  public void setPricelistTypes(List<PricelistPriceListType> pricelistTypes) {
    this.pricelistTypes = pricelistTypes;
  }


  public PricelistPriceListTypeFilter condition(PricelistFilterCondition condition) {
    this.condition = condition;
    return this;
  }

   /**
   * Get condition
   * @return condition
  **/
  @javax.annotation.Nullable
  public PricelistFilterCondition getCondition() {
    return condition;
  }

  public void setCondition(PricelistFilterCondition condition) {
    this.condition = condition;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricelistPriceListTypeFilter pricelistPriceListTypeFilter = (PricelistPriceListTypeFilter) o;
    return Objects.equals(this.pricelistTypes, pricelistPriceListTypeFilter.pricelistTypes) &&
        Objects.equals(this.condition, pricelistPriceListTypeFilter.condition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pricelistTypes, condition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricelistPriceListTypeFilter {\n");
    sb.append("    pricelistTypes: ").append(toIndentedString(pricelistTypes)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pricelistTypes");
    openapiFields.add("condition");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PricelistPriceListTypeFilter
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PricelistPriceListTypeFilter.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PricelistPriceListTypeFilter is not found in the empty JSON string", PricelistPriceListTypeFilter.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PricelistPriceListTypeFilter.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PricelistPriceListTypeFilter` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("pricelistTypes") != null && !jsonObj.get("pricelistTypes").isJsonNull() && !jsonObj.get("pricelistTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `pricelistTypes` to be an array in the JSON string but got `%s`", jsonObj.get("pricelistTypes").toString()));
      }
      // validate the optional field `condition`
      if (jsonObj.get("condition") != null && !jsonObj.get("condition").isJsonNull()) {
        PricelistFilterCondition.validateJsonElement(jsonObj.get("condition"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PricelistPriceListTypeFilter.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PricelistPriceListTypeFilter' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PricelistPriceListTypeFilter> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PricelistPriceListTypeFilter.class));

       return (TypeAdapter<T>) new TypeAdapter<PricelistPriceListTypeFilter>() {
           @Override
           public void write(JsonWriter out, PricelistPriceListTypeFilter value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PricelistPriceListTypeFilter read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PricelistPriceListTypeFilter given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PricelistPriceListTypeFilter
  * @throws IOException if the JSON string is invalid with respect to PricelistPriceListTypeFilter
  */
  public static PricelistPriceListTypeFilter fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PricelistPriceListTypeFilter.class);
  }

 /**
  * Convert an instance of PricelistPriceListTypeFilter to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

