/*
 * pricelist/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PricelistMoney;
import org.openapitools.client.model.PricelistSetPriceListItemPrice;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Pricelist.JSON;

/**
 * PricelistSetPriceListItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T16:16:38.230943551Z[Etc/UTC]")
public class PricelistSetPriceListItem {
  public static final String SERIALIZED_NAME_ITEM_GRN = "itemGrn";
  @SerializedName(SERIALIZED_NAME_ITEM_GRN)
  private String itemGrn;

  public static final String SERIALIZED_NAME_BASE_PRICE = "basePrice";
  @SerializedName(SERIALIZED_NAME_BASE_PRICE)
  private PricelistMoney basePrice;

  public static final String SERIALIZED_NAME_PRICE_ITEMS = "priceItems";
  @SerializedName(SERIALIZED_NAME_PRICE_ITEMS)
  private List<PricelistSetPriceListItemPrice> priceItems;

  public static final String SERIALIZED_NAME_HAS_TIER_PRICES = "hasTierPrices";
  @SerializedName(SERIALIZED_NAME_HAS_TIER_PRICES)
  private Boolean hasTierPrices;

  public PricelistSetPriceListItem() {
  }

  public PricelistSetPriceListItem itemGrn(String itemGrn) {
    this.itemGrn = itemGrn;
    return this;
  }

   /**
   * Get itemGrn
   * @return itemGrn
  **/
  @javax.annotation.Nullable
  public String getItemGrn() {
    return itemGrn;
  }

  public void setItemGrn(String itemGrn) {
    this.itemGrn = itemGrn;
  }


  public PricelistSetPriceListItem basePrice(PricelistMoney basePrice) {
    this.basePrice = basePrice;
    return this;
  }

   /**
   * Get basePrice
   * @return basePrice
  **/
  @javax.annotation.Nullable
  public PricelistMoney getBasePrice() {
    return basePrice;
  }

  public void setBasePrice(PricelistMoney basePrice) {
    this.basePrice = basePrice;
  }


  public PricelistSetPriceListItem priceItems(List<PricelistSetPriceListItemPrice> priceItems) {
    this.priceItems = priceItems;
    return this;
  }

  public PricelistSetPriceListItem addPriceItemsItem(PricelistSetPriceListItemPrice priceItemsItem) {
    if (this.priceItems == null) {
      this.priceItems = new ArrayList<>();
    }
    this.priceItems.add(priceItemsItem);
    return this;
  }

   /**
   * Get priceItems
   * @return priceItems
  **/
  @javax.annotation.Nullable
  public List<PricelistSetPriceListItemPrice> getPriceItems() {
    return priceItems;
  }

  public void setPriceItems(List<PricelistSetPriceListItemPrice> priceItems) {
    this.priceItems = priceItems;
  }


  public PricelistSetPriceListItem hasTierPrices(Boolean hasTierPrices) {
    this.hasTierPrices = hasTierPrices;
    return this;
  }

   /**
   * Get hasTierPrices
   * @return hasTierPrices
  **/
  @javax.annotation.Nullable
  public Boolean getHasTierPrices() {
    return hasTierPrices;
  }

  public void setHasTierPrices(Boolean hasTierPrices) {
    this.hasTierPrices = hasTierPrices;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricelistSetPriceListItem pricelistSetPriceListItem = (PricelistSetPriceListItem) o;
    return Objects.equals(this.itemGrn, pricelistSetPriceListItem.itemGrn) &&
        Objects.equals(this.basePrice, pricelistSetPriceListItem.basePrice) &&
        Objects.equals(this.priceItems, pricelistSetPriceListItem.priceItems) &&
        Objects.equals(this.hasTierPrices, pricelistSetPriceListItem.hasTierPrices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemGrn, basePrice, priceItems, hasTierPrices);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricelistSetPriceListItem {\n");
    sb.append("    itemGrn: ").append(toIndentedString(itemGrn)).append("\n");
    sb.append("    basePrice: ").append(toIndentedString(basePrice)).append("\n");
    sb.append("    priceItems: ").append(toIndentedString(priceItems)).append("\n");
    sb.append("    hasTierPrices: ").append(toIndentedString(hasTierPrices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("itemGrn");
    openapiFields.add("basePrice");
    openapiFields.add("priceItems");
    openapiFields.add("hasTierPrices");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PricelistSetPriceListItem
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PricelistSetPriceListItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PricelistSetPriceListItem is not found in the empty JSON string", PricelistSetPriceListItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PricelistSetPriceListItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PricelistSetPriceListItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("itemGrn") != null && !jsonObj.get("itemGrn").isJsonNull()) && !jsonObj.get("itemGrn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `itemGrn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("itemGrn").toString()));
      }
      // validate the optional field `basePrice`
      if (jsonObj.get("basePrice") != null && !jsonObj.get("basePrice").isJsonNull()) {
        PricelistMoney.validateJsonElement(jsonObj.get("basePrice"));
      }
      if (jsonObj.get("priceItems") != null && !jsonObj.get("priceItems").isJsonNull()) {
        JsonArray jsonArraypriceItems = jsonObj.getAsJsonArray("priceItems");
        if (jsonArraypriceItems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("priceItems").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `priceItems` to be an array in the JSON string but got `%s`", jsonObj.get("priceItems").toString()));
          }

          // validate the optional field `priceItems` (array)
          for (int i = 0; i < jsonArraypriceItems.size(); i++) {
            PricelistSetPriceListItemPrice.validateJsonElement(jsonArraypriceItems.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PricelistSetPriceListItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PricelistSetPriceListItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PricelistSetPriceListItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PricelistSetPriceListItem.class));

       return (TypeAdapter<T>) new TypeAdapter<PricelistSetPriceListItem>() {
           @Override
           public void write(JsonWriter out, PricelistSetPriceListItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PricelistSetPriceListItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PricelistSetPriceListItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PricelistSetPriceListItem
  * @throws IOException if the JSON string is invalid with respect to PricelistSetPriceListItem
  */
  public static PricelistSetPriceListItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PricelistSetPriceListItem.class);
  }

 /**
  * Convert an instance of PricelistSetPriceListItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

