/*
 * pricelist/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import GeminiCommerce_Pricelist.ApiException;
import org.openapitools.client.model.PricelistCreatePriceListRequest;
import org.openapitools.client.model.PricelistCreatePriceListResponse;
import org.openapitools.client.model.PricelistDeletePriceListItemsRequest;
import org.openapitools.client.model.PricelistGetFullPriceItemsRequest;
import org.openapitools.client.model.PricelistGetFullPriceItemsResponse;
import org.openapitools.client.model.PricelistGetPriceItemsByPriceListItemIdsRequest;
import org.openapitools.client.model.PricelistGetPriceItemsByPriceListItemIdsResponse;
import org.openapitools.client.model.PricelistGetPriceListByCodeRequest;
import org.openapitools.client.model.PricelistGetPriceListByCodeResponse;
import org.openapitools.client.model.PricelistGetPriceListItemsRequest;
import org.openapitools.client.model.PricelistGetPriceListItemsResponse;
import org.openapitools.client.model.PricelistGetPriceListRequest;
import org.openapitools.client.model.PricelistGetPriceListResponse;
import org.openapitools.client.model.PricelistGetPricesRequest;
import org.openapitools.client.model.PricelistGetPricesResponse;
import org.openapitools.client.model.PricelistListFullPriceItemsRequest;
import org.openapitools.client.model.PricelistListFullPriceItemsResponse;
import org.openapitools.client.model.PricelistListPriceListsRequest;
import org.openapitools.client.model.PricelistListPriceListsResponse;
import org.openapitools.client.model.PricelistSetPriceListItemsRequest;
import org.openapitools.client.model.PricelistSetPriceListItemsResponse;
import org.openapitools.client.model.PricelistUpdatePriceListRequest;
import org.openapitools.client.model.RpcStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PriceListApi
 */
@Disabled
public class PriceListApiTest {

    private final PriceListApi api = new PriceListApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListCreatePriceListTest() throws ApiException {
        PricelistCreatePriceListRequest body = null;
        PricelistCreatePriceListResponse response = api.priceListCreatePriceList(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListDeletePriceListItemsTest() throws ApiException {
        PricelistDeletePriceListItemsRequest body = null;
        Object response = api.priceListDeletePriceListItems(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListGetFullPriceItemsByPricelistIdTest() throws ApiException {
        PricelistGetFullPriceItemsRequest body = null;
        PricelistGetFullPriceItemsResponse response = api.priceListGetFullPriceItemsByPricelistId(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListGetPriceItemsByPriceListItemIdsTest() throws ApiException {
        PricelistGetPriceItemsByPriceListItemIdsRequest body = null;
        PricelistGetPriceItemsByPriceListItemIdsResponse response = api.priceListGetPriceItemsByPriceListItemIds(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListGetPriceListTest() throws ApiException {
        PricelistGetPriceListRequest body = null;
        PricelistGetPriceListResponse response = api.priceListGetPriceList(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListGetPriceListByCodeTest() throws ApiException {
        PricelistGetPriceListByCodeRequest body = null;
        PricelistGetPriceListByCodeResponse response = api.priceListGetPriceListByCode(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListGetPriceListItemsTest() throws ApiException {
        PricelistGetPriceListItemsRequest body = null;
        PricelistGetPriceListItemsResponse response = api.priceListGetPriceListItems(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListGetPricesItemsTest() throws ApiException {
        PricelistGetPricesRequest body = null;
        PricelistGetPricesResponse response = api.priceListGetPricesItems(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListListFullPriceItemsByPricelistIdTest() throws ApiException {
        PricelistListFullPriceItemsRequest body = null;
        PricelistListFullPriceItemsResponse response = api.priceListListFullPriceItemsByPricelistId(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListListPriceListsTest() throws ApiException {
        PricelistListPriceListsRequest body = null;
        PricelistListPriceListsResponse response = api.priceListListPriceLists(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListSetPriceListItemsTest() throws ApiException {
        PricelistSetPriceListItemsRequest body = null;
        PricelistSetPriceListItemsResponse response = api.priceListSetPriceListItems(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void priceListUpdatePriceListTest() throws ApiException {
        PricelistUpdatePriceListRequest body = null;
        Object response = api.priceListUpdatePriceList(body);
        // TODO: test validations
    }

}
